### ISSUE TITLE
Investigacion authenticacion OATH 

### ISSUE THREAD

**Issue by megadisos** [megadisos/AmateurSportReview#1]
Investigacion authenticacion OATH

**Comment by C-milo** [comment]
Facebook login the steps are:

1. The user will click on "FB Login" button.
2. The user will be asked to login to Facebook and allow permission. If user allows it will return an authorization code.
3. Now we will use the authorization code to get an access token.
4. We can store the access token in session to start a user session.
5. Now we can use the access token to access to different user resources.

Also this article is a tutorial on how to add social authentication to DJango:
https://realpython.com/adding-social-authentication-to-django/
